// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBb3WQwQ2Mer59Q-1YuRjpTc9o7VJ49FU',
    appId: '1:60790859175:web:44f9c030548f1809bd8282',
    messagingSenderId: '60790859175',
    projectId: 'fanum-app',
    authDomain: 'fanum-app.firebaseapp.com',
    databaseURL: 'https://fanum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fanum-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1KQnkUmIRc7YOYJiuqv6AO2UuqJAT6Q',
    appId: '1:60790859175:android:e2a8a618b0958b7fbd8282',
    messagingSenderId: '60790859175',
    projectId: 'fanum-app',
    databaseURL: 'https://fanum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fanum-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLFhIu2nPKNbF_C5UUGkxDqczxukjC1o',
    appId: '1:60790859175:ios:1a2026a1d44010f1bd8282',
    messagingSenderId: '60790859175',
    projectId: 'fanum-app',
    databaseURL: 'https://fanum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fanum-app.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLFhIu2nPKNbF_C5UUGkxDqczxukjC1o',
    appId: '1:60790859175:ios:1a2026a1d44010f1bd8282',
    messagingSenderId: '60790859175',
    projectId: 'fanum-app',
    databaseURL: 'https://fanum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fanum-app.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBb3WQwQ2Mer59Q-1YuRjpTc9o7VJ49FU',
    appId: '1:60790859175:web:b275c9c53836f0ddbd8282',
    messagingSenderId: '60790859175',
    projectId: 'fanum-app',
    authDomain: 'fanum-app.firebaseapp.com',
    databaseURL: 'https://fanum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fanum-app.firebasestorage.app',
  );

}